### ISSUE TITLE
Error: Cannot find module 'through2'

### ISSUE THREAD

**Issue by ronilaukkarinen** [dman777/gulp-newy#3]
Hi. I'm getting this:

```` bash
rolle@bliss:project$ gulp watch

module.js:340
    throw err;
          ^
Error: Cannot find module 'through2'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/rolle/Projects/project/node_modules/gulp-newy/lib/newy.js:1:78)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/rolle/Projects/project/gulpfile.js:24:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
````

My gulpfile.js:

``` javascript
/* 

REQUIRED STUFF
==============
*/

var changed     = require('gulp-changed');
var gulp        = require('gulp');
var imagemin    = require('gulp-imagemin');
var sass        = require('gulp-sass');
var browserSync = require('browser-sync').create();
var notify      = require('gulp-notify');
var prefix      = require('gulp-autoprefixer');
var minifycss   = require('gulp-minify-css');
var uglify      = require('gulp-uglify');
var cache       = require('gulp-cache');
var concat      = require('gulp-concat');
var util        = require('gulp-util');
var header      = require('gulp-header');
var pixrem      = require('gulp-pixrem');
var pagespeed   = require('psi');
var minifyhtml  = require('gulp-htmlmin');
var runSequence = require('run-sequence');
var newy        = require('gulp-newy');
var exec        = require('child_process').exec;

/* 

ERROR HANDLING
==============
*/

var beep = function() {
  var os = require('os');
  var file = '/Users/rolle/gulp_error.wav';
  if (os.platform() === 'linux') {
    // linux
    exec("aplay " + file);
  } else {
    // mac
    console.log("afplay -v 3 " + file);
    exec("afplay -v 3 " + file);
  }
};

var handleError = function(task) {
  return function(err) {
    beep();
    
      notify.onError({
        message: task + ' failed, check the logs..',
        sound: false
      })(err);
    
    util.log(util.colors.bgRed(task + ' error:'), util.colors.red(err));
  };
};

/* 

FILE PATHS
==========
*/

var projectName = 'project'
var themeDir = 'content/themes/'+ projectName;
var imgSrc = themeDir + '/images/*.{png,jpg,jpeg,gif}';
var imgDest = themeDir + '/images/optimized';
var sassSrc = themeDir + '/sass/**/*.{sass,scss}';
var sassFile = themeDir + '/sass/layout.scss';
var cssDest = themeDir + '/css';
var customjs = themeDir + '/js/scripts.js';
var jsSrc = themeDir + '/js/src';
var jsDest = themeDir + '/js';
var markupSrc = [themeDir + '/**/*.php', !'vendor/**/*.php'];
var markupDest = themeDir + '/';

/* 

BROWSERSYNC
===========
*/

gulp.task('browserSync', function() {
    browserSync.init(themeDir, {
        proxy: "project.dev",
        browser: "Google Chrome",
        notify: false
    });
});


/* 

STYLES
======
*/

function sassVersusOneFile(projectDir, srcFile, absSrcFile) {

    var compareFileAgainst = cssDest + "/layout.css";
 
    var destination = path.join(themeDir, compareFileAgainst);
    return destination;
}

gulp.task('styles', function() {
  gulp.src(sassFile)

  .pipe(newy(sassVersusOneFile))
  .pipe(sass({
    compass: false,
    bundleExec: true,
    sourcemap: false,
    style: 'compressed',
    debugInfo: true,
    lineNumbers: true,
    errLogToConsole: true,
    includePaths: require('node-bourbon').includePaths
  })) 

  .on('error', handleError('styles'))
  .pipe(prefix('last 3 version', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4')) //adds browser prefixes (eg. -webkit, -moz, etc.)
  .pipe(minifycss({keepBreaks:false,keepSpecialComments:0,}))
  .pipe(pixrem())
  .pipe(gulp.dest(cssDest))
  .pipe(browserSync.stream());
  });


/* 

IMAGES
======
*/


gulp.task('images', function() {
  var dest = imgDest;

  return gulp.src(imgSrc)

    .pipe(changed(dest)) // Ignore unchanged files
    .pipe(cache(imagemin({ optimizationLevel: 5, progressive: true, interlaced: true }))) //use cache to only target new/changed files, then optimize the images
    .pipe(gulp.dest(imgDest));

});


/* 

SCRIPTS
=======
*/

var currentDate   = util.date(new Date(), 'dd-mm-yyyy HH:ss');
var pkg       = require('./package.json');
var banner      = '/*! <%= pkg.name %> <%= currentDate %> - <%= pkg.author %> */\n';

gulp.task('js', function() {

      gulp.src(
        [
          'bower_components/jquery/dist/jquery.js',
          'bower_components/jquery.easing/js/jquery.easing.js',
          'bower_components/jquery-equalheights/jquery.equalHeights.js',
          'bower_components/slick-carousel/slick/slick.js',
          'bower_components/modernizr/modernizr.js',
          themeDir + '/js/src/imagesloaded.pkgd.js',
          themeDir + '/js/src/jquery-imagefill.js',
          themeDir + '/js/src/mega-site-navigation/jquery.mobile.custom.min.js',
          themeDir + '/js/src/mega-site-navigation/main.js',
          themeDir + '/js/src/scripts.js'
        ])
        .pipe(concat('all.js'))
        .pipe(uglify({preserveComments: false, compress: true, mangle: true}).on('error',function(e){console.log('\x07',e.message);return this.end();}))
        .pipe(header(banner, {pkg: pkg, currentDate: currentDate}))
        .pipe(gulp.dest(jsDest));
});


/*

PAGESPEED
=====

Notes:
   - This runs Google PageSpeed Insights just like here http://developers.google.com/speed/pagespeed/insights/
   - You can use Google Developer API key if you have one, see: http://goo.gl/RkN0vE

*/

gulp.task('pagespeed', pagespeed.bind(null, {
  url: 'http://' + projectName + '.fi',
  strategy: 'mobile'
}));


/*

WATCH
=====

Notes:
   - browserSync automatically reloads any files
     that change within the directory it's serving from
*/

gulp.task('watch', ['browserSync'], function() {
  gulp.watch(sassSrc, ['styles']);
  gulp.watch(imgSrc, ['images']);
  gulp.watch(jsSrc + '/**/*.js', ['js', browserSync.reload]);
});


/* 
BUILD
=====
*/

gulp.task('build', function(cb) {
  runSequence('styles', 'js', 'images', cb);
});

/* 
DEFAULT
=======
*/

gulp.task('default', function(cb) {
    runSequence(
    'images',
    'styles',
    'js',
    'minify-html',
    'browserSync',
    'watch',
    'refresh',
    cb
    );
});
````

My package.json:

```` json
{
  "name": "project",
  "version": "1.0.0",
  "description": "test",
  "author": "Roni Laukkarinen",
  "devDependencies": {
    "browser-sync": "^2.7.13",
    "exec": "0.2.0",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "2.3.1",
    "gulp-cache": "0.2.10",
    "gulp-changed": "^1.2.1",
    "gulp-concat": "2.6.0",
    "gulp-header": "1.2.2",
    "gulp-htmlmin": "1.1.3",
    "gulp-imagemin": "^2.3.0",
    "gulp-minify-css": "1.2.0",
    "gulp-newy": "^1.0.7",
    "gulp-notify": "^2.2.0",
    "gulp-pixrem": "^0.2.3",
    "gulp-sass": "^2.0.3",
    "gulp-uglify": "1.2.0",
    "gulp-util": "^3.0.6",
    "node-bourbon": "^4.2.3",
    "psi": "^1.0.6",
    "require-dir": "^0.3.0",
    "run-sequence": "1.1.1"
  },
  "dependencies": {
    "backbone": "~1.2.1",
    "jquery": "~2.1.4"
  }
}
```

**Comment by dman777** [comment]
@ronilaukkarinen I'm very sorry for the late response. I had notifications turned off for this and did not realize it. 

Thank you so much for filing this bug. The issue was `"through2": "^0.6.3"` was in `devDependencies` when it should of been in `dependencies`. 

 This has been fixed and thank you very much for the issue reported. 

-Darin

**Comment by ronilaukkarinen** [comment]
Thank you very much @dman777!
